version: "3"

services:
  #Database service
  mysql_db:
    container_name: mysql_container
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    volumes:
      # ["./db:/var/lib/mysql"]
      - mysql:/var/lib/mysql

  #Wordpress (image based on Apache)
  wordpress:
    depends_on:
      - mysql_db
    image: wordpress:latest
    restart: always
    ports:
      - "8000:80"
    environment:
      WORDPRESS_DB_HOST: mysql_db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
    volumes:
      [
        "./:/var/www/html",
        "./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini",
      ]

volumes:
  mysql: {}